equalizer:
  frequency: [200, 10000]
  width_q: [0.1, 10.0]
  gain: [-25, 25]
reverb:
  reverberance: [20, 100]
  hf_damping: [10, 100]
  room_scale: [20, 100]
overdrive:
  gain: [0, 20]
  colour: [0, 20]
